version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
  web:
    build: .
    command: ./bin/rails server -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - user_data:/albert_crm/tmp/storage/user_data
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - user_data:/albert_crm/tmp/storage/user_data:ro
    depends_on:
      - db
      - redis
volumes:
  user_data:
