version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/albert_crm
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/albert_crm
    depends_on:
      - db
      - redis
