version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
  web:
    build: .
    command: ./bin/rails server -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/albert_crm
      - type: volume
        source: shared_data
        target: ./user_data
        volume:
          nocopy: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/albert_crm
      - type: volume
        source: shared_data
        target: ./user_data
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - db
      - redis
volumes:
  shared_data:
